version: "3.3" # atau versi yang Anda gunakan

services:
  web:
    # ... (konfigurasi web service Anda) ...
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: crud-mysql-db
    environment:
      MYSQL_DATABASE: crud_app
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: StrongPassword123!
      MYSQL_ROOT_PASSWORD: SuperStrongRootPassword123!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crud_app.sql:/docker-entrypoint-initdb.d/init.sql
    ports: # <--- BAGIAN INI
      - "33060:3306" # Contoh: host_port:container_port dalam tanda kutip, sebagai item list
    restart: unless-stopped

volumes:
  mysql_data:
